import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Sidebar from '../components/Sidebar.js'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chatting App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar />
      
    </div>
  )
}


/*----------------------------------------------------------------*/

// styled components
// material ui / core
// material ui / icons
// firebase
// email validator
// react-firebase-hooks

// get url image from recipients
// build chat screen